server:
  port: 8762
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    prefer-ip-address: false
    hostname: e-2
  client:
    service-url:
      defaultZone: http://admin:123456@e-1:8761/eureka/
    # 向自己注册
    register-with-eureka: true
  #server:
    # 自我保护机制
    #enable-self-preservation: false
    fetch-registry: true